### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by helish88** [UserUNP/Gameboy-Discord#1]
bot just spamming with gifs and don't edit one message 
![image](https://user-images.githubusercontent.com/52331802/120323027-b97dd000-c2ed-11eb-8e49-10e25c7ccf6a.png)

**Comment by UserUNP** [comment]
I am working on a system that wont make the bot spam the gifs

**Comment by helish88** [comment]
ok, thx

**Comment by helish88** [comment]
did u fix?

**Comment by UserUNP** [comment]
i was gonna remake the project in Javascript but then i just got more interested in other things
thanks for bringing this up i was getting bored, gotta *try* to remake it now
